version: "3.9"

services:
  redis:
    image: redis
    restart: always

  website:
    restart: always
    build:
      context: ./website
    ports:
      - "8000:8000"
    command: [ "python3", "./proje/manage.py", "runserver", "0.0.0.0:8000" ]

  worker:
      restart: always
      build:
        context: ./website
      volumes:
        - ./cats:/app/proje/cats
      command: ['celery', '--workdir=./proje', '-A', 'proje', 'worker' ]
